#ifndef __HBEM_DEFINES_H
#define __HBEM_DEFINES_H

#define HBEM_ABS_FILENAME_TOO_LONG 1000
#define HBEM_ILLEGAL_SEARCHPATH 1010
#define HBEM_INVALID_DOMAIN_FILE 1020
#define HBEM_FAILED_TO_OPEN_FILE 1030
#define HBEM_FAILED_TO_WRITE_FILE 1040
#define HBEM_LOGLEVEL_TOO_LOW 1050
#define HBEM_DOMAIN_DATA_MISMATCH 1060
#define HBEM_WRONG_FILE_FORMAT 1070
#define HBEM_INVALID_POINT_DATA 1080
#define HBEM_DUPLICATE_POINT_DATA 1090
#define HBEM_INVALID_SEGMENT_DATA 1100
#define HBEM_INVALID_VERTEX_DATA 1110
#define HBEM_DUPLICATE_SEGMENT_DATA 1120
#define HBEM_INVALID_DOMAIN_DATA 1130
#define HBEM_MISSING_VERTEX_DATA 1140
#define HBEM_DUPLICATE_DOMAIN_DATA 1150
#define HBEM_INVALID_BOUNDARY_DATA 1160
#define HBEM_DUPLICATE_BOUNDARY_DATA 1170
#define HBEM_MISSING_BOUNDARY_DATA 1180
#define HBEM_MISSING_SEGMENT_DATA 1190
#define HBEM_INVALID_MATERIAL_DATA 1200
#define HBEM_DUPLICATE_MATERIAL_DATA 1210
#define HBEM_UNKNOWN_BOUNDARY_CONDITION 1220


#define HBEM_MAX_FILE_PATH_LENGTH  1024   // Size of buffer employed to
                                          // manipulate full file names

#define HBEM_DOMAIN_FILE_FORMAT  "1.0"

#define HBEM_NO_ERROR_MESSAGES        2   // These numbers are used to
#define HBEM_NO_WARNING_MESSAGES      4   // control the verbosity of
#define HBEM_NO_PROGRESS_REPORTS      8   // the solver's log messages

#define HBEM_DEFAULT_VERBOSITY        8   // Default verbosity level



#define HBEM_SHELL_ENV_SEARCHPATH   "HBEM_FILE_SEARCH_PATH"
#define HBEM_PLUGIN_DIRECTORY       "HBEM_PLUGIN_SEARCH_PATH"

#endif     // __HBEM_DEFINES_H
